services:
  - type: web
    name: news-chatbot-backend
    env: node
    repo: https://github.com/rahuljonwal247/news-chatbot-backend
    branch: main
    plan: starter
    buildCommand: npm install
    startCommand: node src/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "5000"
      - key: REDIS_URL
        value: redis://redis:6379
      - key: QDRANT_URL
        value: http://qdrant:6333
      - key: FRONTEND_URL
        value: https://news-chatbot-frontend-q0xj.onrender.com
      - key: LOG_LEVEL
        value: info
      - key: GEMINI_API_KEY
        sync: false
      - key: JINA_API_KEY
        sync: false
